apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail-deployment
  labels:
    app: promtail
    rol: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail-pod
      rol: monitoring
  template:
    metadata:
      labels:
        app: promtail-pod
        rol: monitoring
    spec:
      containers:
        - image: grafana/promtail:2.9.0
          name: promtail-container
          command: 
            - /bin/sh
            - -c
            - -config.file=/etc/promtail/config.yml
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail/config.yml
            - name: nginx-logs
              mountPath: /var/log/nginx
      volumes:
        - name: promtail-config
          configMap:
            name: cm-promtail-config
        - name: nginx-logs
          persistentVolumeClaim:
            claimName: pvc-nginx-logs