apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases

patches:
- target:
    kind: Service
    name: argocd-server
  patch: |
    - op: replace
      path: /spec/type
      value: NodePort
# - target:
#     kind: Secret
#     name: grafana
#   patch: |
#     - op: replace
#       path: /data/admin-password
#       value: SW5nZUVkdWFyCg==