apiVersion: v1
kind: Service
metadata:
  name: web-server-exporter-service
spec:
  selector:
    app: web-server-pod
    rol: exporter
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
  type: NodePort