apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
helmChartInflationGenerator:
- chartName: prometheus
  chartRepoUrl: https://prometheus-community.github.io/helm-charts
  chartVersion: 25.8.1
  releaseName: prometheus
  values: values.yaml