apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
- target:
    kind: Service
    name: argocd-server
  patch: |
    - op: replace
      path: /spec/type
      value: NodePort