apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    app: web-server
    rol: server
spec:
  type: NodePort
  selector:
    app: web-server-pod
    rol: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080