apiVersion: v1
kind: Service
metadata:
  name: loki-service
  labels:
    app: loki
    rol: monitoring
spec:
  type: NodePort
  selector:
    app: loki-pod
    rol: monitoring
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100